-- =====================================================================
-- Organization Café — Migration: posts
-- Activity feed entries (posts) and upcoming events for an organization.
-- =====================================================================

create table public.posts (
    post_id     int generated by default as identity primary key,
    org_id      int not null references public.organizations (org_id) on delete cascade,
    post_type   varchar(20) not null default 'post'
                check (post_type in ('post', 'event')),
    title       varchar(255) not null,
    description text,
    event_date  timestamptz,                     -- only used when post_type = 'event'
    location    varchar(255),
    image       varchar,                         -- storage URL / path
    created_by  int references public.org_reps (org_rep_id) on delete set null,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz
);

create index posts_org_id_idx      on public.posts (org_id);
create index posts_post_type_idx   on public.posts (post_type);
create index posts_event_date_idx  on public.posts (event_date) where event_date is not null;

-- Automatically stamp updated_at on UPDATE.
create extension if not exists moddatetime schema extensions;

create trigger posts_set_updated_at
    before update on public.posts
    for each row execute procedure extensions.moddatetime (updated_at);