-- =====================================================================
-- Organization Café — Migration: page_layouts
-- Custom page layout/theme settings, one row per organization.
-- =====================================================================

create table public.page_layouts (
    layout_id     int generated by default as identity primary key,
    org_id        int not null unique references public.organizations (org_id) on delete cascade,
    theme_color   varchar(20),      -- e.g. hex code
    banner_style  varchar(50),
    section_order text,             -- JSON/array describing section display order
    updated_by    int references public.org_reps (org_rep_id) on delete set null,
    updated_at    timestamptz
);

-- Automatically stamp updated_at on UPDATE.
create extension if not exists moddatetime schema extensions;

create trigger page_layouts_set_updated_at
    before update on public.page_layouts
    for each row execute procedure extensions.moddatetime (updated_at);