-- =====================================================================
-- Organization Café — Migration: admins
-- Maps an authenticated user (auth.users) to an LCO/OSAS admin role.
-- Admin accounts are provisioned OUTSIDE the application (directly at
-- the database level); therefore there are intentionally NO application
-- RLS policies that allow creating admin rows through the API.
-- =====================================================================

create table public.admins (
    admin_id   int generated by default as identity primary key,
    user_id    uuid not null unique references auth.users (id) on delete cascade,
    created_at timestamptz not null default now()
);