-- =====================================================================
-- Organization Café — Migration: media_assets
-- Photos/videos/gifs attached to an organization (e.g., in activity feed).
-- =====================================================================

create table public.media_assets (
    media_id    int generated by default as identity primary key,
    org_id      int not null references public.organizations (org_id) on delete cascade,
    file_url    varchar not null,                -- Supabase Storage path/URL
    media_type  varchar(20) not null default 'image'
                check (media_type in ('image', 'video', 'gif')),
    caption     varchar(255),
    uploaded_by int references public.org_reps (org_rep_id) on delete set null,
    created_at  timestamptz not null default now()
);

create index media_assets_org_id_idx on public.media_assets (org_id);