-- =====================================================================
-- Organization Café — Migration: org_reps
-- Maps an authenticated user (auth.users) to exactly ONE organization.
-- Accounts are created by an admin; there is no public self-registration.
-- =====================================================================

create table public.org_reps (
    org_rep_id int generated by default as identity primary key,
    user_id    uuid not null unique references auth.users (id) on delete cascade,
    org_id     int  not null references public.organizations (org_id) on delete cascade,
    created_by int references public.admins (admin_id) on delete set null,
    created_at timestamptz not null default now()
);

-- user_id already carries a UNIQUE constraint (→ implicit index).
create index org_reps_org_id_idx on public.org_reps (org_id);