-- =====================================================================
-- Organization Café — Migration: announcements
-- Organization announcements (optionally pinned, optionally expiring).
-- =====================================================================

create table public.announcements (
    announcement_id int generated by default as identity primary key,
    org_id          int not null references public.organizations (org_id) on delete cascade,
    title           varchar(255) not null,
    message         text,
    is_pinned       boolean not null default false,
    expires_at      timestamptz,
    created_by      int references public.org_reps (org_rep_id) on delete set null,
    created_at      timestamptz not null default now()
);

create index announcements_org_id_idx      on public.announcements (org_id);
create index announcements_expires_at_idx  on public.announcements (expires_at);