-- =====================================================================
-- Organization Café — Migration: organizations
-- One row per recognized CSU student organization.
-- =====================================================================

create table public.organizations (
    org_id           int generated by default as identity primary key,
    org_name         varchar(255) not null,
    logo             varchar,                    -- Supabase Storage URL
    description      text,
    background_image varchar,                    -- Supabase Storage URL
    fb_page_link     varchar,
    join_form_link   varchar,                    -- external Google Form URL
    join_open_date   timestamptz,                -- join form opens
    join_close_date  timestamptz,                -- join form closes
    category_id      int references public.org_categories (category_id) on delete set null,
    status           varchar(20) not null default 'active'
                     check (status in ('active', 'inactive')),
    created_at       timestamptz not null default now(),
    updated_at       timestamptz
);

-- Supporting indexes for the directory search / discovery engine.
create index organizations_category_id_idx on public.organizations (category_id);
create index organizations_status_idx    on public.organizations (status);
create index organizations_name_idx      on public.organizations (lower(org_name));

-- Automatically stamp updated_at on UPDATE.
create extension if not exists moddatetime schema extensions;

create trigger organizations_set_updated_at
    before update on public.organizations
    for each row execute procedure extensions.moddatetime (updated_at);