-- =====================================================================
-- Organization Café — Migration: org_categories
-- Lookup table of organization categories (e.g., Academic, Cultural,
-- Sports, Religious, etc.).
-- =====================================================================

create table public.org_categories (
    category_id   int generated by default as identity primary key,
    category_name varchar(255) not null unique
);

create index org_categories_name_idx on public.org_categories (category_name);